//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockAnalysis_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotisations
    {
        public int id { get; set; }
        public System.DateTime dateCotisation { get; set; }
        public decimal ouverture { get; set; }
        public decimal fermeture { get; set; }
        public decimal minVal { get; set; }
        public decimal maxVal { get; set; }
        public decimal volFinance { get; set; }
        public decimal volQnte { get; set; }
        public int codeAction { get; set; }
    
        public virtual action action { get; set; }
    }
}
